apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: my-skaffold-config
build:
  googleCloudBuild:
    projectId: ticketing-dev-424311
  artifacts:
    - image: asia-south2-docker.pkg.dev/ticketing-dev-424311/ticketing-dev/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
  tagPolicy:
    envTemplate:
      template: "latest"
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*.yaml
